server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.201.152:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'