server:
  port: 8803
spring:
  application:
    name: cloud-stream-consume
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:  # 这个名字是一个通道的名称
          destination: studyExchange  # 表示要使用Exchange名称定义
          content-type: application/json  # 设置消息类型，本次对象为json 文本为“text/plain”
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          group: atguigu
          consumer:
            partitioned: true  # 开启分区
      instance-count: 2
      instance-index: 1




eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 心跳间隔(默认30s)
    lease-expiration-duration-in-seconds: 5 # 超过这个时间，剔除我(默认90s)
    instance-id: receive-8803.com # 信息列表显示主机名称
    prefer-ip-address: true  # 显示真实主机
