server:
  port: 84
spring:
  application:
    name: nacos-order-consume
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
service:
  url: http://nacos-payment-provider/

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

