server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false 表示自己断就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 访问localhost:7001查看主界面
      defaultZone: http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-eureka-server1